src-git packages https://github.com/The-BB/knc-packages.git
src-git routing https://github.com/The-BB/knc-routing.git
src-git telephony https://github.com/The-BB/knc-telephony.git
src-git golang https://github.com/The-BB/knc-go.git
src-git oldports https://github.com/The-BB/knc-oldpackages-ports.git
src-git rtndev https://github.com/The-BB/knc-rtndev.git
src-git rustlang https://github.com/The-BB/knc-rust.git
#src-git graveyard https://github.com/Entware/graveyard.git
#src-git dvb https://github.com/Entware/entware-dvb.git
src-git kncdev https://github.com/The-BB/kncdev.git
